# Generated by Django 4.1.2 on 2023-06-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicmodel",
            name="thumbnail",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
