# Generated by Django 4.1.2 on 2023-06-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0002_topicmodel_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicmodel",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
