# Generated by Django 4.1.2 on 2023-06-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tech", "0003_techmodel_created_at_techmodel_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="techmodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日"),
        ),
        migrations.AlterField(
            model_name="techmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日"),
        ),
    ]
