# Generated by Django 4.1.2 on 2023-06-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tech", "0004_alter_techmodel_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="techmodel",
            options={"ordering": ["-created_at"]},
        ),
    ]
