# Generated by Django 4.1.2 on 2023-06-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tech", "0005_alter_techmodel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="techmodel",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
