# Generated by Django 4.1.2 on 2023-06-25 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("term", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="termmodel",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="作成日"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="termmodel",
            name="updated_at",
            field=models.DateField(auto_now=True, verbose_name="更新日"),
        ),
    ]
