# Generated by Django 4.1.2 on 2023-06-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("term", "0002_termmodel_created_at_termmodel_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termmodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日"),
        ),
        migrations.AlterField(
            model_name="termmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日"),
        ),
    ]
