# Generated by Django 4.1.2 on 2023-06-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("term", "0003_alter_termmodel_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="termmodel",
            options={"ordering": ["-created_at"]},
        ),
    ]
